// login types
export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const AUTH_ERROR = "AUTH_ERROR";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";

// project types
export const GET_MY_CREATED_PROJECTS = "GET_MY_CREATED_PROJECTS";
export const GET_MY_INVOLVED_PROJECTS = "GET_MY_INVOLVED_PROJECTS";
export const PROJECT_ERROR = "PROJECT_ERROR";

// UI types
export const START_LOCAL_LOADING = "START_LOCAL_LOADING";
export const END_LOCAL_LOADING = "END_LOCAL_LOADING";
export const START_GLOBAL_LOADING = "START_GLOBAL_LOADING";
export const END_GLOBAL_LOADING = "END_GLOBAL_LOADING";
export const START_CREATED_PROJECT_LOADING = "START_CREATED_PROJECT_LOADING";
export const END_CREATED_PROJECT_LOADING = "END_CREATED_PROJECT_LOADING";
export const START_INVOLVED_PROJECT_LOADING = "START_INVOLVED_PROJECT_LOADING";
export const END_INVOLVED_PROJECT_LOADING = "END_INVOLVED_PROJECT_LOADING";
// others
export const SET_DEFAULT = "SET_DEFAULT";
