// user types
export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const AUTH_ERROR = "AUTH_ERROR";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";

// project types
export const GET_MY_CREATED_PROJECTS = "GET_MY_CREATED_PROJECTS";
export const GET_MY_INVOLVED_PROJECTS = "GET_MY_INVOLVED_PROJECTS";
export const PROJECT_ERROR = "PROJECT_ERROR";
export const SET_USERS_LIST = "SET_USERS_LIST";
export const SELECT_USER = "SELECT_USER";
export const SELECT_USER_FROM_TASK = "SELECT_USER_FROM_TASK";
export const MARK_ALREADY_SELECTED_USER = "MARK_ALREADY_SELECTED_USER";
export const EMPTY_USERS_LIST = "EMPTY_USERS_LIST";
export const MARK_ALREDY_SELECTED_USER_FOR_TASK = "MARK_ALREDY_SELECTED_USER_FOR_TASK";

// sprint types
export const GET_SPRINTS = "GET_SPRINTS";
export const SPRINT_ERROR = "SPRINT_ERROR";

// task types
export const GET_TASKS = "GET_TASKS";
export const TASK_ERROR = "TASK_ERROR";
export const GET_SPRINT_DETAILS = "GET_SPRINT_DETAILS";
export const GET_COMMENTS = "GET_COMMENTS";
export const CLEAR_COMMENTS = "CLEAR_COMMENTS";
export const FILTER_TASKS = "FILTER_TASKS";
export const SET_FILTER = "SET_FILTER";
export const SET_FILTER_BY_USER = "SET_FILTER_BY_USER";
export const GET_PROJECT_DETAILS_FOR_TASK = "GET_PROJECT_DETAILS_FOR_TASK";
export const SET_OPEN_TASK_CU_DIALOG = "SET_OPEN_TASK_CU_DIALOG";
export const SET_CLOSE_TASK_CU_DIALOG = "SET_CLOSE_TASK_CU_DIALOG";
export const SET_SELECTED_TASK_FOR_UPDATE = "SET_SELECTED_TASK_FOR_UPDATE";
export const REMOVE_SELECTED_TASK_FOR_UPDATE = "REMOVE_SELECTED_TASK_FOR_UPDATE";

// UI types
export const START_LOCAL_LOADING = "START_LOCAL_LOADING";
export const END_LOCAL_LOADING = "END_LOCAL_LOADING";
export const START_GLOBAL_LOADING = "START_GLOBAL_LOADING";
export const END_GLOBAL_LOADING = "END_GLOBAL_LOADING";
export const START_CREATED_PROJECT_LOADING = "START_CREATED_PROJECT_LOADING";
export const END_CREATED_PROJECT_LOADING = "END_CREATED_PROJECT_LOADING";
export const START_INVOLVED_PROJECT_LOADING = "START_INVOLVED_PROJECT_LOADING";
export const END_INVOLVED_PROJECT_LOADING = "END_INVOLVED_PROJECT_LOADING";
export const START_NOTIFICATION_LOADING = "START_NOTIFICATION_LOADING";
export const END_NOTIFICATION_LOADING = "END_NOTIFICATION_LOADING";

// others
export const SET_DEFAULT = "SET_DEFAULT";
